### ISSUE TITLE
No Records

### ISSUE THREAD

**Issue by inPhilly** [malhal/CloudKit-PHP#9]
Using your code (except modified for my database table), I get no rows every time, even though there are rows in the database. I even remove the filter, and it does not fetch any data. Is there some setting somewhere I might be missing?

**Comment by inPhilly** [comment]
I was just making silly mistakes

**Comment by malhal** [comment]
Sorry I didn't reply earlier I wasn't sure what to say. Glad you got it fixed, please let me know you have any tips I can add to the readme to help others get it working. Thanks.
